export const FETCH_USER_LOGIN = 'FETCH_USER_LOGIN';
export const USER_LOGIN_PENDİGN = 'USER_LOGIN_PENDİGN';
export const USER_LOGIN_REJECTED = 'USER_LOGIN_REJECTED';

export const FETCH_USER_LOGOUT = 'FETCH_USER_LOGOUT';
export const USER_LOGOUT_PENDİGN = 'USER_LOGOUT_PENDİGN';
export const USER_LOGOUT_REJECTED = 'USER_LOGOUT_REJECTED';
