export const FETCH_PRODUCT_LİST = 'FETCH_PRODUCT_LİST';
export const PRODUCT_PENDİGN = 'FETCH_PRODUCT_LİST';
export const PRODUCT_REJECTED = 'FETCH_PRODUCT_LİST';

export const FETCH_ADD_CART_LİST = 'FETCH_ADD_CART_LİST ';
export const ADD_CART_PENDİGN = 'ADD_CART_PENDİGN';
export const ADD_CART_REJECTED = 'ADD_CART_REJECTED';
